/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.controller.ChamadoController;
import br.ulbra.model.Chamado;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno.saolucas
 */
public class ChamadoView extends javax.swing.JFrame {

    /**
     * Creates new form ChamadoView
     */
    public ChamadoView() {
        initComponents();
        listarTabela();
    }

     public void listarTabela() {

        DefaultTableModel model = (DefaultTableModel) tblChamados.getModel();
        model.setRowCount(0);
//solicitante, sala, equipamento_tag, problema_relatado, diagnostico_tecnico, prioridade, status, dataAbertura
        for (Chamado c : controller.listar()) {
            model.addRow(new Object[]{
                c.getId(),
                c.getSolicitante(),
                c.getEquipamentoTag(),
                c.getDiagnosticoTecnico(),
                c.getPrioridade(),
                c.getStatus(),
                c.getDataAbertura()
            });
        }
    }          

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDiagnostico = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChamados = new javax.swing.JTable();
        txtData = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtProblema = new javax.swing.JTextField();
        cbSolicitante = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("GERENCIAR CHAMADOS TÉCNICOS ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 0, -1, -1));

        jLabel2.setText("ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 288, -1));

        jLabel3.setText("NOME DO SOLICITANTE:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel5.setText("TAG DO EQUIPAMENTO:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel6.setText("DIAGNÓSTICO TÉCNICO:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        jPanel1.add(txtDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 288, -1));

        jLabel7.setText("PRIORIDADE:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel8.setText("STATUS:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel9.setText("DATA DE ABERTURA:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        tblChamados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "SOLICITANTE ", "EQUIPAMENTO", "DIAGNÓSTICO", "PRIORIDADE", "STATUS ", "DATA ABERTURA"
            }
        ));
        tblChamados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChamadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChamados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 551, 700, 125));
        jPanel1.add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 288, -1));

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 511, -1, -1));

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 511, -1, -1));

        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 511, -1, -1));

        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 511, -1, -1));

        jLabel10.setText("PROBLEMA");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        txtProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProblemaActionPerformed(evt);
            }
        });
        jPanel1.add(txtProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 288, -1));

        cbSolicitante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 290, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 290, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baixa", "Média", "Alta" }));
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 290, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aberto", "Fechado" }));
        jPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 290, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ChamadoController controller = new ChamadoController();
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
//solicitante, sala, equipamento_tag, problema_relatado, diagnostico_tecnico, prioridade, status, dataAbertura
        String mensagem = controller.cadastrar(
                cbSolicitante.get(),
                txtSala.getText(),
                txtTag.getText(),
                txtProblema.getText(),
                txtDiagnostico.getText(),
                txtPrioridade.getText(),
                txtStatus.getText(),
                txtData.getText()
        );

        javax.swing.JOptionPane.showMessageDialog(null, mensagem);
        listarTabela();

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProblemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProblemaActionPerformed

    private void tblChamadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChamadosMouseClicked
         int linha = tblChamados.getSelectedRow();
        txtId.setText(tblChamados.getValueAt(linha, 0).toString());
        txtSolicitante.setText(tblChamados.getValueAt(linha, 1).toString());
        txtSala.setText(tblChamados.getValueAt(linha, 2).toString());
        txtTag.setText(tblChamados.getValueAt(linha, 3).toString());
        txtProblema.setText(tblChamados.getValueAt(linha, 4).toString());
        txtDiagnostico.setText(tblChamados.getValueAt(linha, 5).toString());
        txtPrioridade.setText(tblChamados.getValueAt(linha, 6).toString());
        txtStatus.setText(tblChamados.getValueAt(linha, 7).toString());
        txtData.setText(tblChamados.getValueAt(linha, 8).toString());
    }//GEN-LAST:event_tblChamadosMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
          int id = Integer.parseInt(txtId.getText());

        String msg = controller.atualizar(
                id, 
                txtSolicitante.getText(),
                txtSala.getText(),
                txtTag.getText(),
                txtProblema.getText(),
                txtDiagnostico.getText(),
                txtPrioridade.getText(),
                txtStatus.getText(),
                txtData.getText()
        );

        JOptionPane.showMessageDialog(null, msg);
        listarTabela();

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
    int id = Integer.parseInt(txtId.getText());

        String msg = controller.atualizar(
                id,
                txtSolicitante.getText(),
                txtSala.getText(),
                txtTag.getText(),
                txtProblema.getText(),
                txtDiagnostico.getText(),
                txtPrioridade.getText(),
                txtStatus.getText(),
                txtData.getText()
        );

        JOptionPane.showMessageDialog(null, msg);
        listarTabela();

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
     txtId.setText(null);
        txtSolicitante.setText(null);
        txtSala.setText(null);
        txtTag.setText(null);
        txtProblema.setText(null);
        txtDiagnostico.setText(null);
        txtPrioridade.setText(null);
        txtStatus.setText(null);
        txtId.setFocusable(true);
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChamadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChamadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChamadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChamadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChamadoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbSolicitante;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblChamados;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDiagnostico;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtProblema;
    // End of variables declaration//GEN-END:variables
}
